XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    BBBBB BBBBBXXXXXXXXXXXXXXXXXXXBBBBBBBB
XXXXXXX
XXXXXX
BBBBB BBBBBBB
BBBBBBBB
BBBBB BBBBBBB
    XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
  XXXXX
BBBBBBBB
XXXXXXX
XXXXXXX