BBBBBBB BBBBBBBBBBBB

BBBBB BBBBBBB
  XXXXXXXX XXXXXXXXX
  BB BBBBBBBBB
  XXXX
    BBB BBBB BB BBBBBBBBB
      XXXX
        XX XXXXXXXXXXXX XX
      XXXXX
    BBBBBB
  XXXXX
  BBBB
    XXXXXXXX XXX XX XXXXX XX XXX XXXXXXXXXXXX
  BBBBB 
BBBBBBBB