# Generated by Django 2.2.3 on 2021-03-27 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('image', models.CharField(max_length=400)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
