# Generated by Django 2.2.3 on 2021-03-29 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagement', '0003_auto_20210327_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 29, 3, 31, 40, 814403), null=True),
        ),
    ]
