# Generated by Django 2.2.3 on 2021-03-29 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagement', '0005_auto_20210329_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2021, 3, 29, 3, 32, 54, 105779, tzinfo=utc)),
        ),
    ]
