# Generated by Django 2.2.3 on 2021-03-31 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagement', '0007_auto_20210329_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 31, 13, 5, 24, 858482, tzinfo=utc), null=True),
        ),
    ]
