# Generated by Django 2.2.3 on 2021-03-31 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagement', '0008_auto_20210331_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 31, 13, 6, 4, 920162, tzinfo=utc), null=True),
        ),
    ]
