# Generated by Django 2.2.3 on 2021-04-01 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagement', '0011_auto_20210401_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 1, 15, 22, 20, 443338, tzinfo=utc), null=True),
        ),
    ]
