# Generated by Django 2.2.3 on 2021-04-02 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagement', '0014_auto_20210402_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 2, 13, 4, 56, 322239, tzinfo=utc), null=True),
        ),
    ]
