# Generated by Django 2.2.3 on 2021-04-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagement', '0017_auto_20210402_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
