# Generated by Django 2.2.3 on 2021-03-27 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('api_token', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.DeleteModel(
            name='BackendUser',
        ),
    ]
