# Generated by Django 2.2.3 on 2021-03-28 20:29

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_auto_20210327_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 20, 29, 9, 883667), null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='api_token',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
