# Generated by Django 2.2.3 on 2021-03-28 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_auto_20210328_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 20, 54, 4, 874478), null=True),
        ),
    ]
