# Generated by Django 2.2.3 on 2021-03-29 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0005_auto_20210328_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 1, 48, 26, 773959), null=True),
        ),
    ]
