# Generated by Django 2.2.3 on 2021-03-29 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0009_auto_20210329_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 3, 32, 35, 165457), null=True),
        ),
    ]
