# Generated by Django 2.2.3 on 2021-03-29 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0011_auto_20210329_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 3, 35, 9, 645959), null=True),
        ),
    ]
