# Generated by Django 2.2.3 on 2021-03-31 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0013_auto_20210331_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 13, 21, 32, 80270), null=True),
        ),
    ]
