# Generated by Django 2.2.3 on 2021-04-01 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0015_auto_20210401_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 14, 10, 18, 580128), null=True),
        ),
    ]
