# Generated by Django 2.2.3 on 2021-04-01 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0016_auto_20210401_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 14, 22, 29, 237369), null=True),
        ),
    ]
