# Generated by Django 2.2.3 on 2021-04-02 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0023_auto_20210402_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 13, 1, 18, 562318), null=True),
        ),
    ]
